// generated by app/build.py from app/miner.js + app/core.js; do not edit
// double SHA-256 over a 128-byte header, nonce = last 16 bytes (words 12..15 of block 2)
const K=new Int32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
const IV=new Int32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]);
const W=new Int32Array(64);
function compress(st,blk){ // st: Int32Array(8) in/out, blk: Int32Array(16)
  for(let i=0;i<16;i++)W[i]=blk[i];
  for(let i=16;i<64;i++){const a=W[i-15],b=W[i-2];
    const s0=((a>>>7)|(a<<25))^((a>>>18)|(a<<14))^(a>>>3);
    const s1=((b>>>17)|(b<<15))^((b>>>19)|(b<<13))^(b>>>10);
    W[i]=(W[i-16]+s0+W[i-7]+s1)|0;}
  let a=st[0],b=st[1],c=st[2],d=st[3],e=st[4],f=st[5],g=st[6],h=st[7];
  for(let i=0;i<64;i++){
    const S1=((e>>>6)|(e<<26))^((e>>>11)|(e<<21))^((e>>>25)|(e<<7));
    const t1=(h+S1+((e&f)^(~e&g))+K[i]+W[i])|0;
    const S0=((a>>>2)|(a<<30))^((a>>>13)|(a<<19))^((a>>>22)|(a<<10));
    const t2=(S0+((a&b)^(a&c)^(b&c)))|0;
    h=g;g=f;f=e;e=(d+t1)|0;d=c;c=b;b=a;a=(t1+t2)|0;}
  st[0]=(st[0]+a)|0;st[1]=(st[1]+b)|0;st[2]=(st[2]+c)|0;st[3]=(st[3]+d)|0;
  st[4]=(st[4]+e)|0;st[5]=(st[5]+f)|0;st[6]=(st[6]+g)|0;st[7]=(st[7]+h)|0;
}
// header: Uint8Array(128). returns object able to hash with a 64-bit nonce (words 14,15)
function makeMiner(header){
  const dv=new DataView(header.buffer,header.byteOffset,128);
  const b1=new Int32Array(16),b2=new Int32Array(16);
  for(let i=0;i<16;i++){b1[i]=dv.getInt32(i*4);b2[i]=dv.getInt32(64+i*4);}
  const mid=new Int32Array(IV);compress(mid,b1);
  const pad=new Int32Array(16);pad[0]=0x80000000|0;pad[15]=1024;
  const st=new Int32Array(8),blk3=new Int32Array(16);blk3[8]=0x80000000|0;blk3[15]=256;
  const out=new Int32Array(8);
  return function hash(nHi,nLo){ // sets nonce words 14,15; result in out (big-endian words)
    b2[14]=nHi;b2[15]=nLo;
    st.set(mid);compress(st,b2);compress(st,pad);
    for(let i=0;i<8;i++)blk3[i]=st[i];
    out.set(IV);compress(out,blk3);
    return out;
  };
}
function lzBits(out){let n=0;for(let i=0;i<8;i++){const w=out[i]>>>0;if(w===0){n+=32;continue;}return n+Math.clz32(w);}return n;}

// ---- chain + star core (shared by page and tests) ----
const ERA_BLOCKS=100000, BASE_REWARD=1000, SHARE_FACTOR=64;
function hexToBytes(h){const b=new Uint8Array(h.length/2);for(let i=0;i<b.length;i++)b[i]=parseInt(h.substr(i*2,2),16);return b;}
function wordsToHex(o){let s='';for(let i=0;i<8;i++)s+=(o[i]>>>0).toString(16).padStart(8,'0');return s;}
function hexToWords(h){const o=new Int32Array(8);for(let i=0;i<8;i++)o[i]=parseInt(h.substr(i*8,8),16)|0;return o;}
function sha32(words){const st=new Int32Array(IV),b=new Int32Array(16);for(let i=0;i<8;i++)b[i]=words[i];b[8]=0x80000000|0;b[15]=256;compress(st,b);return st;}
// threshold: floor(2^64 / E) as [hi,lo] unsigned words
function thrFor(E){const t=(1n<<64n)/BigInt(Math.max(1,Math.round(E)));const c=t>0xFFFFFFFFFFFFFFFFn?0xFFFFFFFFFFFFFFFFn:t;return [Number(c>>32n),Number(c&0xFFFFFFFFn)];}
function shareThr(E){return thrFor(Math.max(1,E/SHARE_FACTOR));}
function below(o,thr){const a=o[0]>>>0,b=o[1]>>>0;return a<thr[0]||(a===thr[0]&&b<thr[1]);}
// header layout (128 bytes): version4 height8 prev32 sharesRoot32 miner20 time8 target8 nonce16
function buildHeader(blk){const h=new Uint8Array(128),dv=new DataView(h.buffer);
  dv.setUint32(0,1);dv.setUint32(4,Math.floor(blk.height/4294967296));dv.setUint32(8,blk.height>>>0);
  h.set(hexToBytes(blk.prev),12);h.set(hexToBytes(blk.shares||'0'.repeat(64)),44);h.set(hexToBytes(blk.miner),76);
  dv.setUint32(96,Math.floor(blk.time/4294967296));dv.setUint32(100,blk.time>>>0);
  dv.setUint32(104,blk.thr[0]);dv.setUint32(108,blk.thr[1]);
  dv.setUint32(112,blk.xn[0]>>>0);dv.setUint32(116,blk.xn[1]>>>0);dv.setUint32(120,blk.nonce[0]>>>0);dv.setUint32(124,blk.nonce[1]>>>0);
  return h;}
function hashBlock(blk){const m=makeMiner(buildHeader(blk));return m(blk.nonce[0]|0,blk.nonce[1]|0);}
function rarityBits(o,thr){const top=(o[0]>>>0)*4294967296+(o[1]>>>0);const t=thr[0]*4294967296+thr[1];if(top<=0)return 40;return Math.max(0,Math.floor(Math.log2(t/top)));}
function verifyChain(blocks){for(let i=0;i<blocks.length;i++){const b=blocks[i];const o=hashBlock(b);const hx=wordsToHex(o);
  if(hx!==b.hash)return {ok:false,at:b.height,why:'hash mismatch'};if(!below(o,b.thr))return {ok:false,at:b.height,why:'above target'};
  if(i>0&&(b.prev!==blocks[i-1].hash||b.height!==blocks[i-1].height+1))return {ok:false,at:b.height,why:'broken link'};}
  return {ok:true,n:blocks.length};}
function rewardAt(h){return BASE_REWARD/Math.pow(2,Math.floor(h/ERA_BLOCKS));}

// ---- star from block ----
const CLASSES=[
 {id:'main',name:'Main sequence',min:0,max:2,odds:'7 in 8'},
 {id:'giant',name:'Giant',min:3,max:4,odds:'1 in 11'},
 {id:'binary',name:'Binary system',min:5,max:6,odds:'1 in 43'},
 {id:'pulsar',name:'Pulsar',min:7,max:9,odds:'1 in 146'},
 {id:'hole',name:'Black hole',min:10,max:999,odds:'1 in 1,024'}];
function classFor(k){return CLASSES.find(c=>k>=c.min&&k<=c.max);}
function prng(words){const s=new Uint32Array(4);for(let i=0;i<4;i++)s[i]=(words[i]^words[i+4])>>>0;if(!(s[0]|s[1]|s[2]|s[3]))s[0]=1;
  return function(){let t=s[3];const s0=s[0];s[3]=s[2];s[2]=s[1];s[1]=s0;t^=t<<11;t^=t>>>8;s[0]=(t^s0^(s0>>>19))>>>0;return s[0]/4294967296;};}
function tempColor(T){T=Math.min(40000,Math.max(1000,T))/100;let r,g,b;
  if(T<=66){r=255;g=99.4708025861*Math.log(T)-161.1195681661;}else{r=329.698727446*Math.pow(T-60,-0.1332047592);g=288.1221695283*Math.pow(T-60,-0.0755148492);}
  if(T>=66)b=255;else if(T<=19)b=0;else b=138.5177312231*Math.log(T-10)-305.0447927307;
  const c=v=>Math.round(Math.min(255,Math.max(0,v)));return [c(r),c(g),c(b)];}
const ON=['v','k','th','s','r','n','l','m','z','dr','kr','ph','t','y','h','qu','sel','ar','or'],VO=['a','e','i','o','u','ae','ai','y','io','ea','ei'],CO=['','','','n','r','s','th','x','l','nd'];
const PLANET_TONES=[[196,120,84],[214,176,122],[120,160,214],[150,200,190],[210,140,170],[170,150,120],[230,210,170],[110,130,170]];
function starFrom(blk){
  const words=hexToWords(blk.hash);const seed=sha32(words);const R=prng(seed);
  const k=blk.height===0?-1:rarityBits(words,blk.thr);const cls=blk.height===0?{id:'origin',name:'Origin',odds:'one of one'}:classFor(k);
  let nm='';const syl=2+(R()<0.35?1:0);for(let i=0;i<syl;i++){nm+=ON[Math.floor(R()*ON.length)]+VO[Math.floor(R()*VO.length)]+(i===syl-1?CO[Math.floor(R()*CO.length)]:'');}
  nm=nm[0].toUpperCase()+nm.slice(1);if(blk.height===0)nm='Origin';
  const s={name:nm,designation:'GX-'+String(blk.height).padStart(6,'0'),cls:cls.id,className:cls.name,odds:cls.odds,k,height:blk.height};
  let T,T2=null,mass=null,period=null,radius,nPl;
  const r=R();
  switch(cls.id){
    case 'main':T=2700+9500*Math.pow(r,2.2);radius=Math.pow(T/5800,1.25)*(0.8+0.4*R());nPl=[0,1,2,3,4,5,6,7,8][Math.floor(Math.pow(R(),1.6)*9)];break;
    case 'giant':if(r<0.6){T=3300+1400*R();s.className='Red giant';}else{T=12000+18000*R();s.className='Blue giant';}radius=10+190*R();nPl=Math.floor(Math.pow(R(),1.5)*5);break;
    case 'binary':T=3000+8000*R();T2=2800+7000*R();radius=Math.pow(T/5800,1.25);nPl=Math.floor(R()*4);break;
    case 'pulsar':T=400000+600000*R();period=Math.round((1.4+Math.pow(R(),2)*900)*10)/10;radius=0.000015;nPl=R()<0.2?1:0;break;
    case 'hole':mass=Math.round((5+55*R())*10)/10;T=null;radius=null;nPl=0;break;
    default:T=5772;radius=1;nPl=3;}
  s.temp=T;s.temp2=T2;s.mass=mass;s.period=period;s.radius=radius;
  s.color=cls.id==='pulsar'?[205,225,255]:cls.id==='hole'?[255,170,90]:tempColor(T);s.color2=T2?tempColor(T2):null;
  s.planets=[];for(let i=0;i<nPl;i++){const tone=PLANET_TONES[Math.floor(R()*PLANET_TONES.length)];s.planets.push({orbit:0.34+i*0.085+R()*0.03,size:2+R()*4.5,tone,ring:R()<0.22,phase:R()*Math.PI*2,speed:0.35/Math.pow(0.34+i*0.09,1.5),moons:Math.floor(Math.pow(R(),2)*4)});}
  // galaxy position (unit disc)
  const era=Math.floor(blk.height/ERA_BLOCKS),arm=era%4;const t=blk.height===0?0:Math.log(1+(blk.height%ERA_BLOCKS||ERA_BLOCKS))/Math.log(1+ERA_BLOCKS);
  const ang=arm*Math.PI/2+t*2.6*Math.PI+(R()-0.5)*0.3;const rad=blk.height===0?0:0.07+0.88*t+(R()-0.5)*0.05;
  s.x=Math.cos(ang)*rad;s.y=Math.sin(ang)*rad;s.twinkle=R()*Math.PI*2;
  return s;}

export {makeMiner,lzBits,thrFor,shareThr,below,buildHeader,hashBlock,rarityBits,verifyChain,starFrom,wordsToHex,hexToWords,sha32,rewardAt,classFor,CLASSES,ERA_BLOCKS};
